sudo: required
dist: trusty

language: java
jdk:
  - oraclejdk8
node_js:
  - "7"

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - nvm install 7
  - cd src/main/java
  - chmod +x mvnw

before_deploy:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - nvm install 7
  - cd src/main/java

deploy:
  provider: heroku
  skip_cleanup: true
  app: m-petstore
  api_key: $HEROKU_KEY
