sudo: required
dist: trusty

language: java
jdk:
  - oraclejdk8

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - chmod +x mvnw
  - cd src/main/java

deploy:
  provider: heroku
  skip_cleanup: true
  api_key: $HEROKU_KEY
  on:
    branch: master